#include <time.h>
#include "test_poly.h"
#include <string.h>
#include <stdio.h>

extern int LLVMFuzzerTestOneInput(const long *data, size_t dataSize) {
	unsigned int dataIndex = 0;
<<<<<<< HEAD
	int dim;
		FILE *fp;
		fp = fopen("out31.txt", "w+");
=======
	long dim;
	FILE *fp;
	fp = fopen("out31.txt", "w+");
>>>>>>> d738476... changed the type of the data generated by libfuzzer from int to long

	if (make_fuzzable_dimension(&dim, data, dataSize, &dataIndex, fp)) {

		elina_manager_t * man = opt_pk_manager_alloc(false);
		opt_pk_array_t * top = opt_pk_top(man, dim, 0);
		opt_pk_array_t * bottom = opt_pk_bottom(man, dim, 0);

		opt_pk_array_t* polyhedron1;
		if (create_polyhedron(&polyhedron1, man, top, dim, data, dataSize,
				&dataIndex, fp)) {
			opt_pk_array_t* polyhedron2;
			if (create_polyhedron(&polyhedron2, man, top, dim, data, dataSize,
					&dataIndex, fp)) {

				//meet == glb, join == lub
				//widening approximates join
				if (!opt_pk_is_leq(man,
						opt_pk_join(man, false, polyhedron1, polyhedron2),
						opt_pk_widening(man, polyhedron1, polyhedron2))) {
					fclose(fp);
					return 1;
				}
			}
		}
	}
	fclose(fp);
	return 0;
}

